# Generated by Django 5.2.4 on 2025-08-10 15:59

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='category',
            field=models.CharField(choices=[('current', 'Current PDF'), ('past', 'Past PDF')], default='past', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(upload_to=backend.models.pdf_upload_path),
        ),
    ]
